#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
#ls="ls -hN --color=auto --group-directories-first" \
alias \
	ls="exa" \
	l="colorls" \
	lt="colorls --tree" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

alias \
	ka="killall" \
	g="git" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	xcp="xclip -selection clipboard" \

alias \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
    vm="/usr/bin/vim" \
	wp="whatsapp-for-linux &>/dev/null & disown" \
	dc="discord &>/dev/null & disown" \
	tg="telegram-desktop &>/dev/null & disown"

alias \
	t="st &>/dev/null & disown"

# Bare git dot config
alias \
	dots='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME' \
    dpp='dots push private priv' \
    dmp='dots push origin master' \
    dcp='dots checkout priv' \
    dcm='dots checkout master' \
	glfsforcerefs="git push origin --force 'refs/heads/*'"

alias lf="/usr/bin/lfrun"
