#!/bin/sh

# Add this when you include flatpak in your system
# dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

xrdb ~/.config/Xresources
mpd &			# music player daemon-you might prefer it as a service though
setbg &			# set the background with the `setbg` script
# Uncomment below for shadows
picom --experimental-backends --backend glx &		# picom for transparency and rounded corners
dunst &			# dunst for notifications
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
#xbindkeys -f ~/.config/xbindkeysrc &
xset r rate 250 40 &	# Speed xrate up
# Switch escape and caps if tty and no passwd required:
sudo -n loadkeys ${XDG_DATA_HOME:-$HOME/.local/share}/keys/ttymaps.kmap 2>/dev/null
unclutter &		# Remove mouse when idle
